### ISSUE TITLE
Typo in model.png

### ISSUE THREAD

**Issue by GuilhermeFreire** [devsisters/multi-speaker-tacotron-tensorflow#4]
There is a typo in the `assets/model.png` image. It reads "GRU i-1  -> GRU i-1 -> GRU i+1" on the middle right portion of the image. I believe it should be "GRU i -1  -> GRU i -> GRU i+1".

**Comment by carpedm20** [comment]
Yes. That should be fixed. But because the diagram is from Deep Voice 2 paper (not drawn by me) so I'll keep it in that way.
